# Generated by Django 3.1.2 on 2020-11-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='CSVData',
        ),
    ]
